cd ..
./spl /home/giri/myexpos/stages/20/BOOT.spl
./spl /home/giri/myexpos/stages/20/console_int.spl
./spl /home/giri/myexpos/stages/20/disk_int.spl
./spl /home/giri/myexpos/stages/20/exp_handler.spl
./spl /home/giri/myexpos/stages/20/int6.spl
./spl /home/giri/myexpos/stages/20/int7.spl
./spl /home/giri/myexpos/stages/20/int8.spl
./spl /home/giri/myexpos/stages/20/int9.spl
./spl /home/giri/myexpos/stages/20/int10.spl
./spl /home/giri/myexpos/stages/20/MOD_0.spl
./spl /home/giri/myexpos/stages/20/MOD_1.spl
./spl /home/giri/myexpos/stages/20/MOD_2.spl
./spl /home/giri/myexpos/stages/20/MOD_4.spl
./spl /home/giri/myexpos/stages/20/MOD_5.spl
./spl /home/giri/myexpos/stages/20/os_startup.spl
./spl /home/giri/myexpos/stages/20/timer.spl
cd ../expl
./expl /home/giri/myexpos/stages/20/odd.expl
./expl /home/giri/myexpos/stages/20/shell.expl
./expl /home/giri/myexpos/stages/20/even.expl
./expl /home/giri/myexpos/stages/20/a2/odd_even_linklist.expl
./expl /home/giri/myexpos/stages/20/temp/temp.expl