cd ..
./spl /home/giri/myexpos/stages/21/BOOT.spl
./spl /home/giri/myexpos/stages/21/console_int.spl
./spl /home/giri/myexpos/stages/21/disk_int.spl
./spl /home/giri/myexpos/stages/21/exp_handler.spl
./spl /home/giri/myexpos/stages/21/int6.spl
./spl /home/giri/myexpos/stages/21/int7.spl
./spl /home/giri/myexpos/stages/21/int8.spl
./spl /home/giri/myexpos/stages/21/int9.spl
./spl /home/giri/myexpos/stages/21/int10.spl
./spl /home/giri/myexpos/stages/21/MOD_0.spl
./spl /home/giri/myexpos/stages/21/MOD_1.spl
./spl /home/giri/myexpos/stages/21/MOD_2.spl
./spl /home/giri/myexpos/stages/21/MOD_4.spl
./spl /home/giri/myexpos/stages/21/MOD_5.spl
./spl /home/giri/myexpos/stages/21/os_startup.spl
./spl /home/giri/myexpos/stages/21/timer.spl
./spl /home/giri/myexpos/stages/21/int11.spl
cd ../expl
./expl /home/giri/myexpos/stages/21/odd.expl
./expl /home/giri/myexpos/stages/21/shell.expl
./expl /home/giri/myexpos/stages/21/even.expl
./expl /home/giri/myexpos/stages/21/gcd.expl
./expl /home/giri/myexpos/stages/21/a2.expl
./expl /home/giri/myexpos/stages/21/pid.expl