cd ..
./spl /home/giri/myexpos/stages/21test/BOOT.spl
./spl /home/giri/myexpos/stages/21test/console_int.spl
./spl /home/giri/myexpos/stages/21test/disk_int.spl
./spl /home/giri/myexpos/stages/21test/exp_handler.spl
./spl /home/giri/myexpos/stages/21test/int6.spl
./spl /home/giri/myexpos/stages/21test/int7.spl
./spl /home/giri/myexpos/stages/21test/int8.spl
./spl /home/giri/myexpos/stages/21test/int9.spl
./spl /home/giri/myexpos/stages/21test/int10.spl
./spl /home/giri/myexpos/stages/21test/MOD_0.spl
./spl /home/giri/myexpos/stages/21test/MOD_1.spl
./spl /home/giri/myexpos/stages/21test/MOD_2.spl
./spl /home/giri/myexpos/stages/21test/MOD_4.spl
./spl /home/giri/myexpos/stages/21test/MOD_5.spl
./spl /home/giri/myexpos/stages/21test/os_startup.spl
./spl /home/giri/myexpos/stages/21test/timer.spl
./spl /home/giri/myexpos/stages/21test/int11.spl
cd ../expl
./expl /home/giri/myexpos/stages/21test/odd.expl
./expl /home/giri/myexpos/stages/21test/shell.expl
./expl /home/giri/myexpos/stages/21test/even.expl
./expl /home/giri/myexpos/stages/21test/gcd.expl
./expl /home/giri/myexpos/stages/21test/a2.expl
./expl /home/giri/myexpos/stages/21test/pid.expl