cd ..
./spl /home/giri/myexpos/stages/22/BOOT.spl
./spl /home/giri/myexpos/stages/22/console_int.spl
./spl /home/giri/myexpos/stages/22/disk_int.spl
./spl /home/giri/myexpos/stages/22/exp_handler.spl
./spl /home/giri/myexpos/stages/22/int6.spl
./spl /home/giri/myexpos/stages/22/int7.spl
./spl /home/giri/myexpos/stages/22/int8.spl
./spl /home/giri/myexpos/stages/22/int9.spl
./spl /home/giri/myexpos/stages/22/int10.spl
./spl /home/giri/myexpos/stages/22/int11.spl
./spl /home/giri/myexpos/stages/22/int13.spl
./spl /home/giri/myexpos/stages/22/int14.spl
./spl /home/giri/myexpos/stages/22/MOD_0.spl
./spl /home/giri/myexpos/stages/22/MOD_1.spl
./spl /home/giri/myexpos/stages/22/MOD_2.spl
./spl /home/giri/myexpos/stages/22/MOD_4.spl
./spl /home/giri/myexpos/stages/22/MOD_5.spl
./spl /home/giri/myexpos/stages/22/os_startup.spl
./spl /home/giri/myexpos/stages/22/timer.spl
./spl /home/giri/myexpos/stages/22/a2/BOOT.spl
./spl /home/giri/myexpos/stages/22/a2/int15.spl
./spl /home/giri/myexpos/stages/22/a2/MOD_0.spl
./spl /home/giri/myexpos/stages/22/a2/MOD_2.spl
./spl /home/giri/myexpos/stages/22/a2/MOD_5.spl
cd ../expl
./expl /home/giri/myexpos/stages/22/odd.expl
./expl /home/giri/myexpos/stages/22/shell.expl
./expl /home/giri/myexpos/stages/22/even.expl
./expl /home/giri/myexpos/stages/22/gcd.expl
./expl /home/giri/myexpos/stages/22/pid.expl
./expl /home/giri/myexpos/stages/22/a1.expl
./expl /home/giri/myexpos/stages/22/a2/child.expl
./expl /home/giri/myexpos/stages/22/a2/parent.expl