cd ..
./spl /home/giri/myexpos/stages/22/a3/BOOT.spl
./spl /home/giri/myexpos/stages/22/a3/console_int.spl
./spl /home/giri/myexpos/stages/22/a3/disk_int.spl
./spl /home/giri/myexpos/stages/22/a3/exp_handler.spl
./spl /home/giri/myexpos/stages/22/a3/int6.spl
./spl /home/giri/myexpos/stages/22/a3/int7.spl
./spl /home/giri/myexpos/stages/22/a3/int8.spl
./spl /home/giri/myexpos/stages/22/a3/int9.spl
./spl /home/giri/myexpos/stages/22/a3/int10.spl
./spl /home/giri/myexpos/stages/22/a3/int11.spl
./spl /home/giri/myexpos/stages/22/a3/int13.spl
./spl /home/giri/myexpos/stages/22/a3/int14.spl
./spl /home/giri/myexpos/stages/22/a3/int15.spl
./spl /home/giri/myexpos/stages/22/a3/MOD_0.spl
./spl /home/giri/myexpos/stages/22/a3/MOD_1.spl
./spl /home/giri/myexpos/stages/22/a3/MOD_2.spl
./spl /home/giri/myexpos/stages/22/a3/MOD_4.spl
./spl /home/giri/myexpos/stages/22/a3/MOD_5.spl
./spl /home/giri/myexpos/stages/22/a3/os_startup.spl
./spl /home/giri/myexpos/stages/22/a3/timer.spl
cd ../expl
./expl /home/giri/myexpos/stages/22/a3/odd.expl
./expl /home/giri/myexpos/stages/22/a3/shell.expl
./expl /home/giri/myexpos/stages/22/a3/even.expl
./expl /home/giri/myexpos/stages/22/a3/gcd.expl
./expl /home/giri/myexpos/stages/22/a3/pid.expl
./expl /home/giri/myexpos/stages/22/a3/a1.expl
./expl /home/giri/myexpos/stages/22/a3/mergecon.expl
./expl /home/giri/myexpos/stages/22/a3/mergesq.expl