cd ..
./spl /home/giri/myexpos/stages/23/BOOT.spl
./spl /home/giri/myexpos/stages/23/console_int.spl
./spl /home/giri/myexpos/stages/23/disk_int.spl
./spl /home/giri/myexpos/stages/23/exp_handler.spl
./spl /home/giri/myexpos/stages/23/int4.spl
./spl /home/giri/myexpos/stages/23/int6.spl
./spl /home/giri/myexpos/stages/23/int7.spl
./spl /home/giri/myexpos/stages/23/int8.spl
./spl /home/giri/myexpos/stages/23/int9.spl
./spl /home/giri/myexpos/stages/23/int10.spl
./spl /home/giri/myexpos/stages/23/int11.spl
./spl /home/giri/myexpos/stages/23/int13.spl
./spl /home/giri/myexpos/stages/23/int14.spl
./spl /home/giri/myexpos/stages/23/int15.spl
./spl /home/giri/myexpos/stages/23/MOD_0.spl
./spl /home/giri/myexpos/stages/23/MOD_1.spl
./spl /home/giri/myexpos/stages/23/MOD_2.spl
./spl /home/giri/myexpos/stages/23/MOD_4.spl
./spl /home/giri/myexpos/stages/23/MOD_5.spl
./spl /home/giri/myexpos/stages/23/os_startup.spl
./spl /home/giri/myexpos/stages/23/timer.spl
echo "expl"
cd ../expl
./expl /home/giri/myexpos/stages/23/odd.expl
./expl /home/giri/myexpos/stages/23/shell.expl
./expl /home/giri/myexpos/stages/23/even.expl
./expl /home/giri/myexpos/stages/23/gcd.expl
./expl /home/giri/myexpos/stages/23/pid.expl
./expl /home/giri/myexpos/stages/23/a1.expl
./expl /home/giri/myexpos/stages/23/a2.expl