cd ..
./spl /home/giri/myexpos/stages/24/BOOT.spl
./spl /home/giri/myexpos/stages/24/console_int.spl
./spl /home/giri/myexpos/stages/24/disk_int.spl
./spl /home/giri/myexpos/stages/24/exp_handler.spl
./spl /home/giri/myexpos/stages/24/int4.spl
./spl /home/giri/myexpos/stages/24/int5.spl
./spl /home/giri/myexpos/stages/24/int6.spl
./spl /home/giri/myexpos/stages/24/int7.spl
./spl /home/giri/myexpos/stages/24/int8.spl
./spl /home/giri/myexpos/stages/24/int9.spl
./spl /home/giri/myexpos/stages/24/int10.spl
./spl /home/giri/myexpos/stages/24/int11.spl
./spl /home/giri/myexpos/stages/24/int13.spl
./spl /home/giri/myexpos/stages/24/int14.spl
./spl /home/giri/myexpos/stages/24/int15.spl
./spl /home/giri/myexpos/stages/24/MOD_0.spl
./spl /home/giri/myexpos/stages/24/MOD_1.spl
./spl /home/giri/myexpos/stages/24/MOD_2.spl
./spl /home/giri/myexpos/stages/24/MOD_3.spl
./spl /home/giri/myexpos/stages/24/MOD_4.spl
./spl /home/giri/myexpos/stages/24/MOD_5.spl
./spl /home/giri/myexpos/stages/24/os_startup.spl
./spl /home/giri/myexpos/stages/24/timer.spl
echo "expl"
cd ../expl
./expl /home/giri/myexpos/stages/24/odd.expl
./expl /home/giri/myexpos/stages/24/shell.expl
./expl /home/giri/myexpos/stages/24/even.expl
./expl /home/giri/myexpos/stages/24/gcd.expl
./expl /home/giri/myexpos/stages/24/pid.expl
./expl /home/giri/myexpos/stages/24/a1.expl
./expl /home/giri/myexpos/stages/24/a2.expl