cd ..
./spl /home/giri/myexpos/stages/24fin/BOOT.spl
./spl /home/giri/myexpos/stages/24fin/console_int.spl
./spl /home/giri/myexpos/stages/24fin/disk_int.spl
./spl /home/giri/myexpos/stages/24fin/exp_handler.spl
./spl /home/giri/myexpos/stages/24fin/int4.spl
./spl /home/giri/myexpos/stages/24fin/int5.spl
./spl /home/giri/myexpos/stages/24fin/int6.spl
./spl /home/giri/myexpos/stages/24fin/int7.spl
./spl /home/giri/myexpos/stages/24fin/int8.spl
./spl /home/giri/myexpos/stages/24fin/int9.spl
./spl /home/giri/myexpos/stages/24fin/int10.spl
./spl /home/giri/myexpos/stages/24fin/int11.spl
./spl /home/giri/myexpos/stages/24fin/int13.spl
./spl /home/giri/myexpos/stages/24fin/int14.spl
./spl /home/giri/myexpos/stages/24fin/int15.spl
./spl /home/giri/myexpos/stages/24fin/MOD_0.spl
./spl /home/giri/myexpos/stages/24fin/MOD_1.spl
./spl /home/giri/myexpos/stages/24fin/MOD_2.spl
./spl /home/giri/myexpos/stages/24fin/MOD_3.spl
./spl /home/giri/myexpos/stages/24fin/MOD_4.spl
./spl /home/giri/myexpos/stages/24fin/MOD_5.spl
./spl /home/giri/myexpos/stages/24fin/os_startup.spl
./spl /home/giri/myexpos/stages/24fin/timer.spl
echo "expl"
cd ../expl
./expl /home/giri/myexpos/stages/24fin/odd.expl
./expl /home/giri/myexpos/stages/24fin/shell.expl
./expl /home/giri/myexpos/stages/24fin/even.expl
./expl /home/giri/myexpos/stages/24fin/gcd.expl
./expl /home/giri/myexpos/stages/24fin/pid.expl
./expl /home/giri/myexpos/stages/24fin/a1.expl
./expl /home/giri/myexpos/stages/24fin/a2.expl