cd ..
./spl /home/giri/myexpos/stages/24test/BOOT.spl
./spl /home/giri/myexpos/stages/24test/console_int.spl
./spl /home/giri/myexpos/stages/24test/disk_int.spl
./spl /home/giri/myexpos/stages/24test/exp_handler.spl
./spl /home/giri/myexpos/stages/24test/int4.spl
./spl /home/giri/myexpos/stages/24test/int5.spl
./spl /home/giri/myexpos/stages/24test/int6.spl
./spl /home/giri/myexpos/stages/24test/int7.spl
./spl /home/giri/myexpos/stages/24test/int8.spl
./spl /home/giri/myexpos/stages/24test/int9.spl
./spl /home/giri/myexpos/stages/24test/int10.spl
./spl /home/giri/myexpos/stages/24test/int11.spl
./spl /home/giri/myexpos/stages/24test/int13.spl
./spl /home/giri/myexpos/stages/24test/int14.spl
./spl /home/giri/myexpos/stages/24test/int15.spl
./spl /home/giri/myexpos/stages/24test/MOD_0.spl
./spl /home/giri/myexpos/stages/24test/MOD_1.spl
./spl /home/giri/myexpos/stages/24test/MOD_2.spl
./spl /home/giri/myexpos/stages/24test/MOD_3.spl
./spl /home/giri/myexpos/stages/24test/MOD_4.spl
./spl /home/giri/myexpos/stages/24test/MOD_5.spl
./spl /home/giri/myexpos/stages/24test/os_startup.spl
./spl /home/giri/myexpos/stages/24test/timer.spl
echo "expl"
cd ../expl
./expl /home/giri/myexpos/stages/24test/odd.expl
./expl /home/giri/myexpos/stages/24test/shell.expl
./expl /home/giri/myexpos/stages/24test/even.expl
./expl /home/giri/myexpos/stages/24test/gcd.expl
./expl /home/giri/myexpos/stages/24test/pid.expl
./expl /home/giri/myexpos/stages/24test/a1.expl
./expl /home/giri/myexpos/stages/24test/a2.expl